---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: capstone-project
    labels:
      app: capstone-project
    namespace: default
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: capstone-project
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: capstone-project
      spec:
        containers:
        - image: fabioj/capstone-project:latest
          imagePullPolicy: Always
          name: capstone-project
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            limits:
              cpu: "0.5"
              memory: 200Mi
            requests:
              cpu: "0.2"
              memory: "150"

---
  apiVersion: v1
  kind: Service
  metadata:
    name: capstone-project-service
  spec:
    selector:
      app: capstone-project
    type: LoadBalancer
    ports:
     - protocol: TCP
       targetPort: 80
       port: 80
